# Generated by Django 5.0.2 on 2024-03-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_usermodel_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='surname',
        ),
    ]
