# Generated by Django 4.2.7 on 2024-03-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_remove_task_due_date_task_finish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finish_date',
            new_name='end_date',
        ),
    ]
