# Generated by Django 4.2.7 on 2024-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
