# Generated by Django 4.2.7 on 2024-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0015_alter_task_comments_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('highht', 'Yüksek')]),
        ),
    ]
