# Generated by Django 4.2.7 on 2024-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0016_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('hight', 'Yüksek')]),
        ),
    ]
